require("priyanshu.remap")
require("priyanshu.packer")
require("priyanshu.colors")
require("priyanshu.lsp")
require("priyanshu.treesitter")
require("priyanshu.cmp")
require("mason").setup()
require("priyanshu.none-ls")
